### ISSUE TITLE
Custom patterns for generating file names using Dependency Injection

### ISSUE THREAD

**Issue by AndreasBaumgart** [AndreasBaumgart/Zend_Filter_ImageSize#2]
At the moment it's not possible to generate custom file name patterns without overriding getThumbnailBasename() and thus creating a subclass of Zend_Filter_ImageSize. This shouldn't be necessary as the process of generating a file name is just a supplying part and could also reside in a different object, which can be injected on call.

**Comment by travisfisher** [comment]
Has this been addressed? I need exactly this functionality and I don't want to have to subclass.

**Comment by AndreasBaumgart** [comment]
Yes. Have a look at the latest revision on master and the examples in `tests/ExamplesTest.php`. 

The idea is to implement `Polycast_Filter_ImageSize_PathBuilder_Interface` and pass it to the filter via `$filter->setOutputPathBuilder($yourBuilderInstance)`.

I rewrote the whole library though. The API changed somewhat and the namespace is not longer `Zend` but `Polycast`. But apart from that it still does the same job.
