### ISSUE TITLE
Bug in Humongous example?

### ISSUE THREAD

**Issue by alolis** [AndreasBaumgart/Zend_Filter_ImageSize#3]
Hello,

I am trying to use that example and set my own name for the produced files. In the mentioned example there is a call to $config->setName(...) but that method does not exist in the Polycast_Filter_ImageSize_Configuration_Standard class nor seems implemented in the NamedConfig class of the example. Am I missing something here?

Thanks for your time

**Comment by AndreasBaumgart** [comment]
Oh, you are right. You aren't missing anything, there was a mistake in the example. The NamedConfig class in the example expects the name passed to the constructor and not by using a setter method (this has been the case at an earlier version of the example).

Has been fixed. Thanks for reporting!

**Comment by alolis** [comment]
Thanks for the quick response :)
